### ISSUE TITLE
Adding "database" to the website

### ISSUE THREAD

**Issue by JullianMQ** [JullianMQ/Akaru#2]
# Tasklist for the database side of the backend
- [x] Add a development branch for database
- [x] Connect to the firestore database
## User collection
- [x] Connect the firestore database to the authentication 
- [x] Read the data for the logged in user
- [x] Write books to the borrowed books array
- [x] Update their borrowed books
- [x] Returned books should be deleted from user "borrowedBooks" key
## Book Collection
- [ ] Read all the books, should see if they are available or not
- [ ] Update book status that are not available/borrowed (SHOULD REFLECT AT PAGE)
- [x] Update book document to see userID when borrowed
## Admin 
- [x] Add new books
- [x] Update info for books
- [x] Delete books
- [x] Be able to delete users (essentially like a ban)
## Firestore rules
- [x]  Write firestore rules that are contained for user
- [x]  Firestore rules for admin, where they can access everything

**Comment by JullianMQ** [comment]
@KentxStuuki pa update pag na accept na ni jose ung invite sa repo, para ma assign ko sya dito.

Pa update nalang din, lagyan mo check if done na ung task. 
Add another issue if need ma break down ung isang task. Thanks.

**Comment by JullianMQ** [comment]
The two tasks left are beyond the scope of the project. Closing the issue now

**Comment by Chister555** [comment]
nu to?
